version: "3"

services:

  nginx:
    image: nginx:1.23.4-alpine3.17
    container_name: test_project_nginx
    working_dir: /code
    restart: always
    volumes:
      - ../:/code/:consistent
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - fpm
    ports:
      - "8088:80"
    networks:
      - test_project_network

  fpm:
    image: t1nkl/php-alpine:fpm-8.2
    container_name: test_project_fpm
    working_dir: /code
    restart: always
    volumes:
      - ../:/code/:consistent
    entrypoint: /code/.docker/php-fpm/entrypoint.sh
    links:
      - postgres
    networks:
      - test_project_network
      - test_project_db

#  mysql:
#    image: mysql:8.0.32
#    container_name: test_project_mysql
#    restart: 'no'
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=test_project_db
#    ports:
#      - "3308:3306"
#    networks:
#      - test_project_db

  postgres:
    image: postgres:15.2-alpine3.17
    container_name: test_project_postgres
    restart: 'no'
    environment:
      POSTGRES_DB: test_project_db
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - "5438:5432"
    networks:
      - test_project_db

networks:
  test_project_network:
    external: true
  test_project_db:
    external: true
